### ISSUE TITLE
Installation documentation 

### ISSUE THREAD

**Issue by DrMattG** [CoLRev-Environment/bib-dedupe#11]
https://github.com/openjournals/joss-reviews/issues/6318

For people who are non-"native" python users (like me!) it would be really nice to give more details about how to install the package. Maybe point to some useful resources that can get a user past the first hurdle... Many systematic reviewers want to try new tools but fall at the first hurdle of installation and understanding jargon around code.

**Comment by geritwagner** [comment]
Thank you for raising this issue. I agree that the instructions should make the setup easier for users who are new to the Python ecosystem. Let me work on it and update the docs accordingly.

**Comment by geritwagner** [comment]
I have updated the docs with a separate installation page explaining the steps to setup Python on different platforms ([here](https://colrev-environment.github.io/bib-dedupe/installation.html)). I decided to merge/push to the main branch, which automatically updates the documentation. The setup steps currently take inspiration from the asreview project. Do you think the new page works?

**Comment by DrMattG** [comment]
This works for me! I really like it and it has helped me hugely as I stumble through Python!! (I usually code in R....)
