### ISSUE TITLE
Example dataset?

### ISSUE THREAD

**Issue by DrMattG** [CoLRev-Environment/bib-dedupe#13]
https://github.com/openjournals/joss-reviews/issues/6318
Would it be possible to have an example dataset for users to use in the example workflow so they don't have to go and find a file in the correct format? I am not sure if you can add datasets to a python package like you can with R packages but there must be an elegant solution to that.

**Comment by geritwagner** [comment]
I just noticed that the data files are not distributed with the regular Python installation. I will post an update once I have a solution.

**Comment by geritwagner** [comment]
Ok, now the datasets should be available. I just tested it successfully after installing the Package from GitHub.
