### ISSUE TITLE
Comments on manuscript

### ISSUE THREAD

**Issue by DrMattG** [CoLRev-Environment/bib-dedupe#15]
https://github.com/openjournals/joss-reviews/issues/6318

Line 68: "We define duplicates as potentially differing bibliographic representations..." - who is "we" in this sentence? (see also line 121; line 124; line 174; line 175, line 192)
Line 79: "A journal paper and a reprint..." - Why is this not considered a duplicate? This case strikes me as odd - it is the same study.
Tables - It would be good for the reader for the tables to have a caption and for them to be referenced in the text
Tables - can you explain (in the text or caption) what all the abbreviations mean.

**Comment by geritwagner** [comment]
Thank you for your comments on the manuscript. I addressed them as follows:

- replaced "we" with "I" (2fe8543bd251bb2f966953e7b7ee5c845615caef).
- included a paragraph explaining that different reports of the same study are not considered duplicates in this stage. As stated in the Cochrane handbook, it is good practice to link same studies after full-text retrieval, relying on information from the documents, external registers, manual assessment by the review team, and potentially involving the consultation of the authors of the original reports. (6a941f2d0bcdd3bf4c353eead8ea918f8736f97e).
- updated the tables with captions and abbreviations (cfb61c68f706adf8473b00009a6cb799b51046a5).

I hope my changes align with your expectations. I will leave the issue open for your responses or additional comments (if any).
