### ISSUE TITLE
Cannot import name "load_example_data"

### ISSUE THREAD

**Issue by DrMattG** [CoLRev-Environment/bib-dedupe#18]
https://github.com/openjournals/joss-reviews/issues/6318

Probably me doing something wrong but I get this error: "ImportError: cannot import name 'load_example_data' from 'bib_dedupe.bib_dedupe' " 

I have re-installed the package.

**Comment by geritwagner** [comment]
Can you install the latest version from GitHub or the repository (using one the following commands)?

```
pip install git+https://github.com/CoLRev-Environment/bib-dedupe
pip install . # run in the bib-dedupe directory on main branch
```

With `pip install bib-dedupe` or `pip install .` on paper branch, an older version would be installed, potentially explaining the error. The `pip install bib-dedupe` (via PyPI) will install the latest changes once I create a new release. Does `load_example_data` with any of the two installation options above?

**Comment by geritwagner** [comment]
Wondering whether my suggestions are helpful. Please let me know if there is anything I can do to help with the next steps.

**Comment by geritwagner** [comment]
As a quick update: I released new versions of BibDedupe to PyPI. This means `load_example_data` should now be available when running `pip install bib-dedupe`. Please let me know whether this solves the issue or whether it still persists.

**Comment by geritwagner** [comment]
The import of `load_example_data` from `bib_dedupe.bib_dedupe` should work on the main branch and the current PyPI version (see #25). Please feel free to reopen the issue if you can confirm the ImportError in the current version on PyPI or the main branch.
